# Site settings
title: Mohit Surana
description: Mohit Surana's portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mohit Surana
user_title: Developer | ML Enthusiast
email: msurana@cs.umass.edu
github_username:  mohit_surana
linkedin_username: mohitsurana
# twitter_username: mohit_surana
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
   id: "UA-22540019-3"

exclude: ['package.json', 'src' , 'node_modules']
